insert into endereco (logradouro, numero, bairro, cidade, estado, cep) values ('Rua Três', '338', 'Vila Industrial', 'Piracicaba','SP','13412233');
insert into endereco (logradouro, numero, bairro, cidade, estado, cep) values ('Rua Ulisses Bueno', '175', 'Vila Rosa', 'Aparecida de Goiânia','GO','74935870');
insert into endereco (logradouro, numero, bairro, cidade, estado, cep) values ('Rua Domingos Vendemiati', '154', 'Parque Recanto do Parrilho', 'Jundiaí','SP','13219051');
insert into endereco (logradouro, numero, bairro, cidade, estado, cep) values ('Rua Ângelo Alberto Nesti', '639', 'Bussocaba', 'Osasco','SP','06053060');
insert into endereco (logradouro, numero, bairro, cidade, estado, cep) values ('SQN 507, Bl C', '500', 'Asa Norte', 'Brasília','DF','71020050');
insert into endereco (logradouro, numero, bairro, cidade, estado, cep) values ('CA 5', '103', 'Centro de Atividades', 'Brasília','DF','71440650');
insert into pessoa (type, endereco_id) values ('juridica', 1);
insert into pessoa (type, endereco_id) values ('fisica', 2);
insert into pessoa (type, endereco_id) values ('juridica', 3);
insert into pessoa (type, endereco_id) values ('juridica', 4);
insert into pessoa (type, endereco_id) values ('juridica', 5);
insert into pessoa (type, endereco_id) values ('fisica', 6);
insert into pessoa_juridica (cnpj, nome_fantasia, razao_social, id) values ('11.941.838/0001-04', 'Elisa e Flávia Pães e Doces ME', 'Pães e Doces', 1);
insert into pessoa_fisica (cpf, nome_completo, id) values ('763.679.800-08', 'Mirella Kamilly Letícia Barbosa', 2);
insert into pessoa_juridica (cnpj, nome_fantasia, razao_social, id) values ('92.456.516/0001-63', 'Arthur e Andreia Telas Ltda', 'Telas', 3);
insert into pessoa_juridica (cnpj, nome_fantasia, razao_social, id) values ('87.009.263/0001-40', 'Lavínia e Tereza Locações de Automóveis Ltda', 'Loc., Auto', 4);
insert into pessoa_juridica (cnpj, nome_fantasia, razao_social, id) values ('63.458.851/0001-15', 'JP Gestão Ltda', 'JP Gestão', 5);
insert into pessoa_fisica (cpf, nome_completo, id) values ('000.000.000-00', 'Jackson Pertusatti', 6);
insert into empresa(telefone, pessoa_id, pessoa_juridica_id) values('(19) 9 8838-0630',2, 1);
insert into empresa(telefone, pessoa_id, pessoa_juridica_id) values('(11) 9 9572-6906',4, 3);
insert into empresa(telefone, pessoa_id, pessoa_juridica_id) values('(61) 9 9222-4334',6, 5);
